version: '3.1'
services:
  db:
    image: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - PG_HOST=db
      - NODE_ENV=production
    ports:
      - 3001:3000
    depends_on:
      - db